#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright © contributors to CNPG Extensions.
# SPDX-License-Identifier: Apache-2.0
"""Stage the interpreter and its resolved native dependencies for an image volume."""
import os
from pathlib import Path
import re
import shutil
import subprocess


def output(*args):
    return subprocess.check_output(args, text=True).strip()


def copy(source, destination):
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


root = Path('/out')
major = os.environ['PG_MAJOR']
package = f'postgresql-plperl-{major}'
for directory in ('lib', 'share/extension', 'system', 'licenses', 'source'):
    (root / directory).mkdir(parents=True, exist_ok=True)
for line in output('dpkg', '-L', package).splitlines():
    source = Path(line)
    if not source.is_file():
        continue
    for prefix, destination in ((f'/usr/lib/postgresql/{major}/lib/', 'lib'),
                                (f'/usr/share/postgresql/{major}/', 'share')):
        if line.startswith(prefix):
            copy(source, root / destination / line[len(prefix):])

# Perl's configured directories differ by Debian suite and architecture.
for key, destination in (('archlib', 'arch'), ('privlib', 'share'),
                         ('vendorarch', 'vendor-arch'), ('vendorlib', 'vendor-share')):
    directory = output('perl', '-MConfig', '-e', f'print $Config{{{key}}}')
    if Path(directory).is_dir():
        shutil.copytree(directory, root / 'perl' / destination, symlinks=False)

packages = {package, 'libdbi-perl', 'libdbd-pg-perl'}
for line in output('dpkg-query', '-W', '-f=${binary:Package}\t${db:Status-Status}\n').splitlines():
    name, status = line.split('\t')
    if status == 'installed' and re.match(r'^(libperl[0-9]|perl-modules-)', name):
        packages.add(name)


# Include owners of all copied interpreter/module trees, including Debian split
# packages. Generated bytecode follows its source module's package accounting.
trees = [output('perl', '-MConfig', '-e', f'print $Config{{{key}}}') for key in ('archlib', 'privlib', 'vendorarch', 'vendorlib')]
for tree in trees:
    if not Path(tree).is_dir():
        continue
    owners = subprocess.run(['dpkg-query', '-S', str(Path(tree).resolve()) + '/*'], capture_output=True, text=True)
    packages.update(re.findall(r'^([a-z0-9][a-z0-9+.-]*(?::[a-z0-9]+)?): /', owners.stdout, re.M))

libraries = set()
for path in root.rglob('*'):
    if not path.is_file():
        continue
    with path.open('rb') as file:
        if file.read(4) != b'\x7fELF':
            continue
    linked = output('ldd', str(path))
    if 'not found' in linked:
        raise RuntimeError(f'Unresolved native dependency: {path}\n{linked}')
    libraries.update(re.findall(r'=> (/\S+)', linked))

for library in sorted(libraries):
    path = Path(library)
    if re.match(r'^(lib(c|m|pthread|dl|rt|resolv|util)\.so\.|ld-linux)', path.name):
        continue  # Matching CNPG base supplies the glibc runtime and loader.
    copy(path, root / 'system' / path.name)
    candidates = [str(path), str(path.resolve())]
    candidates += [p[4:] for p in candidates if p.startswith('/usr/')]
    for candidate in candidates:
        found = subprocess.run(['dpkg-query', '-S', candidate], capture_output=True, text=True)
        owners = re.findall(r'^([a-z0-9][a-z0-9+.-]*(?::[a-z0-9]+)?): /', found.stdout, re.M)
        if found.returncode == 0 and owners:
            packages.add(owners[0])
            break
    else:
        raise RuntimeError(f'No package owner for {path}')

sources = set()
manifest = []
for name in sorted(packages):
    details = output('dpkg-query', '-W', '-f=${binary:Package}\t${Version}\t${Architecture}\t${source:Package}\t${source:Version}', name)
    manifest.append(details)
    fields = details.split('\t')
    short = name.split(':')[0]
    copyright = Path('/usr/share/doc') / short / 'copyright'
    if not copyright.exists():
        raise RuntimeError(f'Missing license notice for {name}')
    copy(copyright, root / 'licenses' / short / 'copyright')
    # Ship exact sources for all redistributed runtime packages, including
    # Debian patches and build rules. PostgreSQL itself is permissively licensed.
    if name != package:
        sources.add((fields[3], fields[4]))
(root / 'licenses/runtime-packages.tsv').write_text('\n'.join(manifest) + '\n')
(root / 'licenses/base-packages.tsv').write_text(output('dpkg-query', '-W', '-f=${binary:Package}\t${Version}\t${Architecture}\n', 'libc6', f'postgresql-{major}') + '\n')
shutil.copytree('/usr/share/common-licenses', root / 'licenses/common-licenses')
for name, version in sorted(sources):
    subprocess.run(['apt-get', 'source', '--download-only', f'{name}={version}'], cwd=root / 'source', check=True)
(root / 'licenses/source-packages.tsv').write_text(''.join(f'{n}\t{v}\n' for n, v in sorted(sources)))
